config/routes.rb
Rails.application.routes.draw do

  resources :suggestions, only: [:index, :create]
  resources :analytics, only: [:index]

  resources :users, only: [:index, :show]
  resources :users, path: "u", as: "usrs", only: [:index, :show]

  resources :categories, only: [:index, :show]
  resources :categories, path: "c", as: "cats", only: [:index, :show]

  resources :packages, only: [:index, :show]
  resources :packages, path: "p", as: "pkgs", only: [:index, :show]

  resource :trending, controller: "trending", only: [:show]
  root to: 'trending#show'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/views/home/_package_list.html.erb
<% offset = ( params[:page] || '1' ).to_i - 1 %>
<% offset *= WillPaginate.per_page %>

<% packages.each_with_index do |package, index| %>

  <% offset_index = offset + index %>

  <% unless offset_index.zero? %>

    <div class="list-group-separator"></div>

  <% end %>

  <div class='list-group-item col-xs-11'>

    <div class='row-picture'>

      <i class='circle' alt='icon'>

        <%= offset_index + 1 %>
      </i>

    </div>

    <div class='row-content'>

      <h4 class='list-group-item-heading'>
        <%= link_to package.name, package_path(package.name) %>
      </h4>

      <p class='list-group-item-text'>
        <%= truncate package.description, length: 50 %>
      </p>

    </div>

  </div>

  <div class='col-xs-1 cs-pull-right cs-package-stars'>

    <h4 class='row'>
      <i class='material-icons'>star_rate</i>
      <span><%= package.stargazers_count %></span>
    </h4>

  </div>

<% end %>