config/routes.rb
Rails.application.routes.draw do

  resources :suggestions, only: [:index, :create]
  resources :analytics, only: [:index]

  resources :users, only: [:index, :show]
  resources :users, path: "u", as: "usrs", only: [:index, :show]

  resources :categories, only: [:index, :show]
  resources :categories, path: "c", as: "cats", only: [:index, :show]

  resources :packages, only: [:index, :show]
  resources :packages, path: "p", as: "pkgs", only: [:index, :show]

  resource :trending, controller: "trending", only: [:show]
  root to: 'trending#show'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id           :bigint           not null, primary key
#  labels_count :integer
#  name         :string
#  slug         :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#
# Indexes
#
#  index_categories_on_labels_count  (labels_count)
#  index_categories_on_slug          (slug) UNIQUE
#
class Category < ApplicationRecord

  extend FriendlyId
  friendly_id :name, use: :slugged

  has_many :labels, dependent: :destroy
  has_many :packages, through: :labels

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    all_categories = Category.where.not(name: "Trending").order(labels_count: :desc).to_a

    category_names = $category_map.keys
    @categories = all_categories.select { |cur_category| category_names.include? cur_category.name }

    sub_category_names = $category_map.values.flatten
    @sub_categories = all_categories.select { |cur_category| sub_category_names.include? cur_category.name }

    @categories.each do |cur_category|
      cur_value = $category_map[cur_category.name]

      cur_sub_categories = @sub_categories.select do |tmp_category|
        cur_value.include? tmp_category.name
      end

      if ( cur_sub_categories.length < 2 )
        @sub_categories.reject! { |sub_category| cur_sub_categories.include? sub_category }
        cur_sub_categories = []
      end
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    set_packages @category.packages
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.friendly.find(params[:id].downcase)
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/_index_categories.html.erb
<div class="flex flex-col">
  <div class="-my-2 py-2 overflow-x-auto sm:-mx-6 sm:px-6 lg:-mx-8 lg:px-8">
    <div class="align-middle inline-block min-w-full shadow overflow-hidden sm:rounded-lg border-b border-gray-200 rounded-md">
      <table class="min-w-full">
        <thead>
          <tr>
            <th class="px-3.5 py-3 border-b border-gray-200 bg-gray-50 text-center text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">#</th>
            <th class="px-6 py-3 border-b border-gray-200 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">
              Category
            </th>
            <th colspan="2" class="px-6 py-3 border-b border-gray-200 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">
              Top 2 Sub Categories
            </th>
          </tr>
        </thead>
        <tbody>

          <%
            cloned_dict = Hash[
              $category_dict.keys.map{
                |cur_key| @categories.select{ |tmp_category| tmp_category.slug == cur_key }.first
              }.zip($category_dict.values)
            ]
          %>

          <% cloned_dict.each_with_index do |(category, sub_categories), cur_index| %>
            <%
              sub_category_list = Array.new(2) { |i| sub_categories[i] }
            %>

            <tr class="<%= cur_index.even? ? 'bg-white' : 'bg-gray-50' %>">
              <td class="px-3.5 whitespace-no-wrap text-sm text-center leading-5 text-gray-500">
                <%= cur_index + 1 %>
              </td>
              <td class="px-6 py-4 whitespace-no-wrap text-sm leading-5 font-medium text-gray-900">
                <%= link_to category.name, cat_path(category, init_params) %>
              </td>
              <% sub_category_list.each do |sub_category| %>
                <td class="px-6 py-4 whitespace-no-wrap text-sm leading-5 text-gray-500">
                  <% if sub_category.present? %>
                    <%= link_to sub_category.name, cat_path(sub_category, init_params) %>
                  <% else %>
                    -
                  <% end %>
                </td>
              <% end %>
            </tr>

          <% end %>

        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/categories/_index_sub_categories.html.erb
<div class="bg-white shadow rounded-md">
  <div class="bg-white px-4 py-5 sm:px-6 rounded-md">
    <div class="-ml-4 -mt-2 flex items-center justify-between flex-wrap sm:flex-no-wrap">
      <div class="ml-4 mt-2">
        <h3 class="text-lg leading-6 font-medium text-gray-900">
          Sub Categories
        </h3>
      </div>
      <div class="ml-4 mt-2 flex-shrink-0">

        <div x-data="{ open: false }" @keydown.window.escape="open = false" @click.away="open = false" class="relative inline-block text-left">
          <div>
            <span class="rounded-md shadow-sm">
              <button @click="open = !open" type="button" class="inline-flex justify-center w-full rounded-md border border-gray-300 px-4 py-2 bg-white text-sm leading-5 font-medium text-gray-700 hover:text-gray-500 focus:outline-none focus:border-blue-300 focus:shadow-outline-blue active:bg-gray-50 active:text-gray-800 transition ease-in-out duration-150 js-dropdown-button__subcategory">
                <div class="js-dropdown-button-text" style="white-space: nowrap; overflow: hidden; text-overflow: ellipsis; max-width: 15vw;">
                  <% if params[:sub_category].present? && params[:sub_category] != 'all' %>
                    <%= Category.friendly.find(params[:sub_category]).name %>
                  <% else %>
                    All
                  <% end %>
                </div>
                <svg class="-mr-1 ml-2 h-5 w-5" fill="currentColor" viewBox="0 0 20 20">
                  <path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd"/>
                </svg>
              </button>
            </span>
          </div>
          <div x-show="open" x-transition:enter="transition ease-out duration-100" x-transition:enter-start="transform opacity-0 scale-95" x-transition:enter-end="transform opacity-100 scale-100" x-transition:leave="transition ease-in duration-75" x-transition:leave-start="transform opacity-100 scale-100" x-transition:leave-end="transform opacity-0 scale-95" class="origin-top-right absolute right-0 mt-2 w-56 rounded-md shadow-lg" style="display: none;">
            <div class="rounded-md bg-white shadow-xs">
              <div class="py-1">
                <%= link_to categories_path(init_params.merge({ sub_category: 'all' })), '@click' => "open = !open", class: "js-category-button block px-4 py-2 text-sm leading-5 text-gray-700 hover:bg-gray-100 hover:text-gray-900 focus:outline-none focus:bg-gray-100 focus:text-gray-900 #{ 'hidden' unless params[:sub_category].present? && params[:sub_category] != 'all' }" do %>
                  All
                <% end %>
                <% @categories.each do |category| %>
                  <% next unless $category_dict.has_key? category.slug %>
                  <% next if $category_dict[category.slug].count.zero? %>

                  <%= link_to categories_path(init_params.merge({ sub_category: category.slug })), '@click' => "open = !open", class: "js-category-button block px-4 py-2 text-sm leading-5 text-gray-700 hover:bg-gray-100 hover:text-gray-900 focus:outline-none focus:bg-gray-100 focus:text-gray-900 #{ 'hidden' if category.slug == params[:sub_category]}" do %>
                    <%= category.name %>
                  <% end %>

                <% end %>
              </div>
            </div>
          </div>
        </div>

      </div>
    </div>
  </div>
  <ul class="js-sub-categories-list">
    <% sub_category_package_threshold = 9 %>

    <% @sub_categories.each do |sub_category| %>
      <li class="border-t border-gray-200 <%= 'js-few-packages' if sub_category.labels_count < sub_category_package_threshold %>">
        <%= link_to cat_path(sub_category, init_params), class: "block hover:bg-gray-50 focus:outline-none focus:bg-gray-50 transition duration-150 ease-in-out" do %>
          <div class="px-4 py-4 flex items-center sm:px-6">
            <div class="min-w-0 flex-1 sm:flex sm:items-center sm:justify-between">
              <div>
                <div class="text-sm leading-5 truncate">
                    <span class="font-medium text-indigo-600"><%= sub_category.name %></span>
                    <span class="text-gray-400">(<%= sub_category.labels_count %>)</span>
                </div>
                <div class="mt-2 flex">
                  <div class="flex items-center text-sm leading-5 text-gray-500">
                    <span class="js-from-span">
                      from <%= $sub_category_dict[sub_category.slug].name %> Category
                    </span>
                  </div>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </li>
    <% end %>
  </ul>

  <a href="javascript:void(0)" class="bg-gray-50 border-t border-gray-200 block hover:bg-white focus:outline-none focus:bg-white transition duration-150 ease-in-out js-more-categories">
    <div class="py-4">
      <div class="text-center items-center justify-between js-view-all">
        View more categories
      </div>
    </div>
  </a>

</div>

<script>
  function refreshSubCategoryList() {
    categoryName = $(".js-dropdown-button-text").text().trim();

    if ( categoryName == "All" ) {
      $('.js-more-categories').removeClass("hidden");

      $("ul.js-sub-categories-list li:not(.js-few-packages)").removeClass("hidden");
      $("ul.js-sub-categories-list li.js-few-packages").addClass("hidden");

      return
    }

    $('.js-more-categories').addClass("hidden");

    selectedInnerText = "from " + categoryName + " Category";

    $("ul.js-sub-categories-list li").each(function (curIndex, curElement) {
      tmpInnerText = curElement.getElementsByClassName("js-from-span")[0].innerText.trim();

      if ( tmpInnerText == selectedInnerText ) {
        $(curElement).removeClass("hidden");
      } else {
        $(curElement).addClass("hidden");
      }
    });
  }

  refreshSubCategoryList();

  $(".js-category-button").on("click", function(curEvent) {
    categoryName = curEvent.target.text.trim();
    $(".js-dropdown-button-text").text(categoryName);

    refreshSubCategoryList();

    setTimeout(function(){
      $(".js-category-button").removeClass("hidden");
      $(curEvent.target).addClass("hidden");
    }, 333);

    history.replaceState({}, "", curEvent.target.href);
    ga('send', 'pageview', curEvent.target.href);

    curEvent.preventDefault();
    return false;
  })

  $(".js-tab__sub-cateogries").on("click", function () {
    categoryName = $(".js-dropdown-button-text").text("All");
    refreshSubCategoryList();

    if ( $(".js-category-button:visible").length > 0 ) {
      $(".js-dropdown-button__subcategory").click();
    }

    setTimeout(function(){
      $(".js-category-button:not(:first-of-type)").removeClass("hidden");
      $(".js-category-button:first-of-type").addClass("hidden");
    }, 333);
  })

  $('.js-more-categories').on("click", function (curEvent) {
    $("ul.js-sub-categories-list li.js-few-packages").removeClass("hidden");
    $('.js-more-categories').addClass("hidden");

    curEvent.preventDefault();
  })
</script>

app/views/categories/_index_tabs.html.erb
<div>

  <div class="max-w-7xl mx-auto px-8">
    <div class="sm:hidden">
      <select class="form-select block w-full js-category-select">
        <option <%= 'selected' unless params[:sub_category].present? %>>Categories</option>
        <option <%= 'selected' if params[:sub_category].present? %>>Sub Categories</option>
      </select>
    </div>
  </div>

  <div class="hidden sm:block mb-4">
    <div class="border-b border-gray-200">
      <nav class="-mb-px flex">
        <%= link_to categories_path(init_params), class: "cs-category-tab js-tab__cateogries #{ 'active' unless params[:sub_category].present? }" do %>
          Categories
        <% end %>

        <%= link_to categories_path(init_params.merge({ sub_category: 'all' })), class: "cs-category-tab js-tab__sub-cateogries #{ 'active' if params[:sub_category].present? }" do %>
          Sub Categories
        <% end %>
      </nav>
    </div>
  </div>

</div>

<script>
  function toggleCategoryTab(tabName) {
    $(".cs-category-tab").removeClass("active");

    if ( tabName == "Sub Categories") {
      $(".js-category").addClass("hidden");
      $(".js-sub-category").removeClass("hidden");
      $(".js-tab__sub-cateogries").addClass("active");
    } else if ( tabName == "Categories") {
      $(".js-category").removeClass("hidden");
      $(".js-sub-category").addClass("hidden");
      $(".js-tab__cateogries").addClass("active");
    } else {
      alert("[1] Bad Tab Name: " + tabName)
    }
  }

  $(".cs-category-tab").on("click", function(curEvent) {
    var valueSelected = curEvent.target.textContent.trim();
    toggleCategoryTab(valueSelected)

    $(".js-category-select").val(valueSelected);

    history.replaceState({}, "", curEvent.target.href);
    ga('send', 'pageview', curEvent.target.href);

    curEvent.preventDefault();
    return false;
  })

  $(".js-category-select").on("change", function(curEvent) {
    var valueSelected = this.value;

    if ( valueSelected == "Sub Categories") {
      $(".js-tab__sub-cateogries").click();
    } else if ( valueSelected == "Categories") {
      $(".js-tab__cateogries").click();
    } else {
      alert("[2] Bad Tab Name: " + valueSelected)
    }

    toggleCategoryTab(valueSelected)
  })
</script>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<div class="h-screen flex overflow-hidden bg-gray-100" x-data="{ sidebarOpen: false }" @keydown.window.escape="sidebarOpen = false">

  <%= render partial: 'layouts/index_sidebar' %>

  <div class="flex flex-col w-0 flex-1 overflow-hidden">

    <%= render partial: 'layouts/index_navbar' %>

    <main class="cs-index-main">

      <%
        init_params = {
          order: params[:order], sort: params[:sort],
          min_stars: params[:min_stars], since: params[:since],
          depth: params[:depth], registered: params[:registered]
        }

        init_params.delete_if { |k, v| !v.present? }
      %>

      <%= render partial: "index_tabs", locals: { init_params: init_params } %>

      <div class="max-w-2xl mx-auto px-8 js-sub-category <%= 'hidden' unless params[:sub_category].present? %>">
        <div class="pt-5 mt-0.5 pb-4 mb-2">
          <%= render partial: "index_sub_categories", locals: { init_params: init_params } %>
        </div>
      </div>

      <div class="max-w-7xl mx-auto px-8 js-category <%= 'hidden' if params[:sub_category].present? %>">
        <div class="pt-5 mt-0.5 pb-4 mb-2">
          <%= render partial: "index_categories", locals: { init_params: init_params } %>
        </div>
      </div>

    </main>

  </div>

</div>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<% content_for :page_title, @category.name %>

<%= render partial: 'layouts/index_javascript' %>

<div class="h-screen flex overflow-hidden bg-gray-100" x-data="{ sidebarOpen: false }" @keydown.window.escape="sidebarOpen = false">

  <%= render partial: 'layouts/index_sidebar' %>

  <div class="flex flex-col w-0 flex-1 overflow-hidden">

    <%= render partial: 'layouts/index_navbar' %>

    <main class="cs-index-main" x-data onscroll="loadNextPage()">

      <%= render partial: 'layouts/index_tabs', locals: { cur_path: :cat_path, cur_id: @category.slug } %>

      <%= render partial: 'layouts/index_list', locals: { package_header: @category.name } %>

      <div id="div_next_link">
        <%= render partial: 'layouts/next_link' %>
      </div>

    </main>

  </div>

</div>

<%= render partial: 'layouts/filter_modal', locals: { cur_path: :cat_path, cur_id: @category.slug } %>